
# Changes here will be overwritten by Copier
_commit: 0.9.1
_src_path: gh:leroyvn/copier-pdm
author_email: vincent.leroy@rayference.eu
author_fullname: Vincent Leroy
author_username: leroyvn
copyright_date: '2022'
copyright_holder: Vincent Leroy
copyright_holder_email: vincent.leroy@rayference.eu
copyright_license: MIT
docs_sphinx: false
project_description: Pint meets attrs
project_name: Pinttrs
python_conda_env_name: pinttrs
python_package_command_line_name: pinttrs
python_package_distribution_name: pinttrs
python_package_import_name: pinttr
repository_name: pinttrs
repository_namespace: leroyvn
repository_provider: github.com
use_precommit: false

