[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [{ name = "Vincent Leroy", email = "vincent.leroy@rayference.eu" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering",
]
dependencies = ["pint>=0.20"]
description = "Unit contexts for Pint."
keywords = ["pint", "units", "quantities"]
license = "MIT"
license-files = ["LICENSE"]
name = "pintext"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0.dev0"

[project.optional-dependencies]
all = ["pintext[attrs,pydantic,xarray]"]
attrs = ["attrs>=22.2"]
pydantic = ["pydantic>=2.0"]
xarray = ["xarray>=2023.1.0"]

[project.urls]
Changelog = "https://github.com/rayference/pintext/blob/main/CHANGELOG.md"
Documentation = "https://pintext.readthedocs.io"
Homepage = "https://github.com/rayference/pintext"
Issues = "https://github.com/rayference/pintext/issues"
Repository = "https://github.com/rayference/pintext"

[tool.coverage.html]
directory = "./reports/coverage/html"

[tool.coverage.json]
output = "./reports/coverage/coverage.json"

[tool.coverage.paths]
equivalent = ["src/", "__pypackages__/"]

[tool.coverage.report]
omit = ["src/*/__init__.py", "src/*/_version.py"]
precision = 2
show_missing = true
skip_covered = true

[tool.coverage.run]
branch = true
parallel = true
source = ["src/"]

[tool.hatch.build.targets.wheel]
packages = ["src/pintext"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest]
addopts = [
  "-ra",
  "-vv",
  "--strict-config",
  "--strict-markers",
  "--doctest-glob=*.rst",
  "--doctest-modules",
]
filterwarnings = ["error"]
log_level = "INFO"
minversion = "9.0"
norecursedirs = [".git", ".env", "dist", "build", "__pypackages__"]
python_files = ["test_*.py", "*_test.py", "tests.py"]
testpaths = ["tests", "docs", "src"]
xfail_strict = true

[tool.ruff.lint]
extend-select = ["B", "E", "F", "I", "UP"]

[tool.ty.src]
include = ["src"]

[tool.ruff.lint.isort]
relative-imports-order = "closest-to-furthest"

[dependency-groups]
docs = [
  "shibuya>=2024",
  "sphinx-autobuild>=2021.3",
  "sphinx-autodoc-typehints",
  "sphinx-copybutton>=0.4",
  "sphinx-design>=0.5",
  "sphinx-iconify>=0.3",
  "sphinx>=7",
  "myst-parser>=0.16",
]
test = ["pytest-cov>=3.0", "pytest>=9.0", "numpy>=1.24.4", "xdoctest>=0.15.0"]
dev = [
  { include-group = "test" },
  { include-group = "docs" },
  "ruff>=0.15.4",
  "setuptools>=69.1.1",
  "taskipy>=1.10",
  "ty>=0.0.20",
]

[tool.repo-review]
ignore = [
  "PY007", # repo-review recommends nox for task running, but be use taskipy
  "PC111",
  "PC140",
  "PC160",
  "PC170",
  "PC180",
  "MY", # TODO (typing)
]

[tool.taskipy.tasks]
docs = "sphinx-build -b html docs docs/_build/html"
docs-clean = "rm -rf docs/_build/"
docs-serve = "sphinx-autobuild docs docs/_build/html"
docs-lock = "uv export --format requirements.txt --all-extras --group docs --no-hashes -o requirements/docs.txt"
test = "pytest"
